### ISSUE TITLE
Flow runs only in client not in agent, remains Pending

### ISSUE THREAD

**Issue by fatjoni** [flavienbwk/prefect-docker-compose#13]
I am trying to deploy my flows using the client (local agent) and the weather.py runs only ones as it is executed in the client docker container, while the agent is online but does not pic any task. Any ideas?

**Comment by flavienbwk** [comment]
Hi @fatjoni, try removing the hash-looking tag from your agent on the UI.
This blocks agents from executing flows.

**Comment by fatjoni** [comment]
![hashlooking label](https://user-images.githubusercontent.com/7958688/103155433-32598880-47a0-11eb-8c38-9a5ce996df22.PNG)

Thanks for getting back to me, i am not sure i quite understand what you are referring to, do you mean the hash label as in screenshot? I cant find a way to remove it. Can you give me some hint pls?
Thanks a lot!

**Comment by flavienbwk** [comment]
Exactly. Sorry it's been some time I've used Prefect, try instead adding this tag in your flow tags.

**Comment by fatjoni** [comment]
WOW! I would have never guessed that labels did this much! Thanks a lot!!

**Comment by flavienbwk** [comment]
You're welcome. However I'm sure there's a cleaner way to solve this problem. Not sure it's the "official" way to do it but I didn't  investigate further.

I'm interested if you find the "right way" to do it in Prefect!

**Comment by fatjoni** [comment]
Well, i noticed i could add this tag to the agent --no-hostname-label, but there was no similar tag for the flows, basically for the first time you are running a flow you have to remove the hash tag manually and later on even through the updates the label won't be coming back.

**Comment by ruslanruslanruslan** [comment]
So may anybody clarify please how to remove tag from agent? I can't find such option.

**Comment by kopicee** [comment]
@fatjoni the "equivalent" of `--no-hostname-label` for flows is set during flow creation:
```py
import prefect
from prefect.storage import Local

with Flow('example', storage=Local(add_default_labels=False)) as flow:
    pass

flow.register(project_name='...', labels=[])  # not needed, but you can check in case
```
Then when registering the flow, the label should no longer be automatically added, unless you are passing additional labels to `flow.register()`.
