### ISSUE TITLE
Agent is not working

### ISSUE THREAD

**Issue by ruslanruslanruslan** [flavienbwk/prefect-docker-compose#14]
Hi!
I've successfully run docker-compose for server and agent. Server works fine with normal agents. But if agent working inside docker-compose on the same host where server docker-compose runs, then agent is visible but it doesn't get tasks, all of them stays in pending status.
How can I debug this problem? No errors found, agent in success stay, but flows not going.

**Comment by flavienbwk** [comment]
Hi @ruslanruslanruslan, that's a known behavior. Please check this solution : https://github.com/flavienbwk/prefect-docker-compose/issues/13#issuecomment-751383003
