### ISSUE TITLE
Add Prefect Runners to the architecture diagrams and explain the mechanism

### ISSUE THREAD

**Issue by bklaubos** [flavienbwk/prefect-docker-compose#15]
Currently, in "The Operation Principles of Prefect", the various Prefect Runners are not shown and how they interact with the Prefect Agents to bring about task execution.
IMO, this is the weakest link in official Prefect doc of not  showing the mechanics of how everything fit together on the backends.

**Comment by flavienbwk** [comment]
Could you provide an example of interaction ? Thanks.
