### ISSUE TITLE
Invalid link 

### ISSUE THREAD

**Issue by patrikfejda** [flavienbwk/prefect-docker-compose#40]
In README, there is a link on text [through a Deployment](https://github.com/flavienbwk/prefect-docker-compose/blob/main/client/weather.py#L53) to https://github.com/flavienbwk/prefect-docker-compose/blob/main/client/weather.py#L53

It returns 404

**Comment by flavienbwk** [comment]
Thank you for pointing this out ! This was fixed in PR #41
